export const GETINPUTFOCUS = 'get_input_focus'
export const GETINPUTBLUR = 'get_input_blur'
export const GETSEARCHLIST = 'get_search_list'
export const GETMOUSEENTER = 'get_mouse_enter'
export const GETMOUSELEAVE = 'get_mouse_leave'